#Super user access
sudo: required
#Get docker and install
services:
    - docker

before_install:
    - docker build -t harsittheking001/docker-react -f Dockerfile.dev .

script:
    - docker run harsittheking001/docker-react npm run test